entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  docker: {}

# Define TLS certificates statically
tls:
  certificates:
    - certFile: "/certs/selfsigned.crt"
      keyFile: "/certs/selfsigned.key"

log:
  level: DEBUG